import { Poppins, Inter } from 'next/font/google';
import ClientWrapper from './clientWrapper';
import './globals.css';
import Preloader from './Components/Preloader/Preloader';
import SmoothCursor from './Components/CustomCursor/CustomCursor';
const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <>
          <SmoothCursor />
          {/* <Preloader /> */}
          <ClientWrapper>{children}</ClientWrapper>
        </>
      </body>
    </html>
  );
}
